pipeline:
  name: Run Terraform Configuration
  identifier: Run_Terraform_Configuration
  projectIdentifier: AWM
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Harness Terraform Execution
        identifier: Harness_Terraform_Execution
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: Terraform Plan
                  identifier: Terraform_Plan
                  spec:
                    provisionerIdentifier: harness_<+pipeline.variables.organization_id>_<+pipeline.variables.project_id>
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            gitFetchType: Branch
                            branch: <+input>
                            folderPath: /
                            connectorRef: terraformharnessprojectonboarding
                          type: Git
                        moduleSource:
                          useConnectorCredentials: true
                      environmentVariables:
                        - name: HARNESS_ENDPOINT
                          value: <+stage.variables.HARNESS_ENDPOINT>
                          type: String
                        - name: HARNESS_ACCOUNT_ID
                          value: <+stage.variables.HARNESS_ACCOUNT_ID>
                          type: String
                        - name: HARNESS_PLATFORM_API_KEY
                          value: <+stage.variables.HARNESS_PLATFORM_API_KEY>
                          type: String
                      varFiles:
                        - varFile:
                            spec:
                              content: |-
                                # [Required] Provide an organization reference ID.  Must exist before execution
                                organization_id = "<+pipeline.variables.organization_id>"

                                # [Required] New project identifier
                                project_id = "<+pipeline.variables.project_id>"

                                # [Required] New project name
                                project_name = "<+pipeline.variables.project_name>"

                                # [Required] JPMC SEAL
                                seal_id = "<+pipeline.variables.seal_id>"

                                # [Required] JPMC DevX Project Name
                                devx_project_name = "<+pipeline.variables.devx_project_name>"

                                # [Optional] JPMC Project Code. Defaults to DevX Project Name if not provided.
                                project_code = "<+pipeline.variables.project_code>"

                                # [Required] JPMC Project Code. Defaults to DevX Project Name if not provided.
                                bitbucket_url = "<+pipeline.variables.bitbucket_url>"

                                # [Required] JPMC Project Code. Defaults to DevX Project Name if not provided.
                                validation_repo = "<+pipeline.variables.validation_repo>"

                                # [Required] JPMC Project Code. Defaults to DevX Project Name if not provided.
                                aws_artifactory_url = "<+pipeline.variables.aws_artifactory_url>"

                                # [Required] JPMC Project Code. Defaults to DevX Project Name if not provided.
                                generic_artifactory_url = "<+pipeline.variables.generic_artifactory_url>"
                            identifier: terraform.tfvars
                            type: Inline
                      secretManagerRef: harnessSecretManager
                      skipStateStorage: false
                      skipRefreshCommand: false
                  timeout: 10m
              - step:
                  type: TerraformApply
                  name: Terraform Apply
                  identifier: Terraform_Apply
                  spec:
                    provisionerIdentifier: harness_<+pipeline.variables.organization_id>_<+pipeline.variables.project_id>
                    configuration:
                      type: InheritFromPlan
                  timeout: 10m
        tags: {}
        variables:
          - name: HARNESS_ENDPOINT
            type: String
            description: Enter the Harness Platform URL.  Defaults to Harness SaaS URL
            required: true
            value: https://app.harness.io/gateway
          - name: HARNESS_ACCOUNT_ID
            type: String
            description: Enter the Harness Platform Account Number
            required: true
            value: <+account.identifier>
          - name: HARNESS_PLATFORM_API_KEY
            type: Secret
            description: Enter the Harness Platform API Key for your account
            required: true
            value: account.harness_platform_key
  variables:
    - name: organization_id
      type: String
      description: "[Required] Provide an organization reference ID.  Must exist before execution"
      required: true
      value: <+input>
    - name: project_id
      type: String
      description: "[Required] New project identifier"
      required: true
      value: <+input>
    - name: project_name
      type: String
      description: "[Required] New project name"
      required: true
      value: <+input>
    - name: seal_id
      type: String
      description: "[Required] JPMC SEAL"
      required: true
      value: <+input>
    - name: devx_project_name
      type: String
      description: "[Required] JPMC DevX Project Name"
      required: true
      value: <+input>
    - name: project_code
      type: String
      description: "[Optional] JPMC Project Code. Defaults to DevX Project Name if not provided."
      required: true
      value: <+input>
    - name: bitbucket_url
      type: String
      description: "[Required] JPMC Project Code. Defaults to DevX Project Name if not provided."
      required: true
      value: <+input>
    - name: validation_repo
      type: String
      description: "[Required] JPMC Project Code. Defaults to DevX Project Name if not provided."
      required: true
      value: <+input>
    - name: aws_artifactory_url
      type: String
      description: "[Required] JPMC Project Code. Defaults to DevX Project Name if not provided."
      required: true
      value: <+input>
    - name: generic_artifactory_url
      type: String
      description: "[Required] JPMC Project Code. Defaults to DevX Project Name if not provided."
      required: true
      value: <+input>
